import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "./provider";

export const metadata: Metadata = {
  title: "Volume Up",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </QueryProvider>
  );
}
